# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17aqSLITVR4D91n2JpcnhzYgRUJ0OulwG
"""

print("Buger Boy !")
print("Menu")
print("1.Burger – Rs.500")
print("2.Pizza – Rs.1000")
print("3.Juice – Rs.300")
print("4.Milk Shake - Rs.800")
choice = int(input("Choose items (1-3):"))
quantity = int(input("Enter Quantity:"))

if choice == 1:
 total = 500*quantity
elif choice == 2:
  total = 1000*quantity
elif choice == 3:
  total = 300*quantity
else:
  total = 0

print("Total bill:", total)
